.TH "cpptest-compileroutput.h" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpptest-compileroutput.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include 'cpptest\-output\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTest::CompilerOutput\fP"
.br
.RI "Compiler-like output handler\&. "
.ti -1c
.RI "class \fBTest::CompilerOutput::InvalidFormat\fP"
.br
.RI "Compiler output exception\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTest\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
