.TH "cpptest-output.h" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpptest-output.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTest::Output\fP"
.br
.RI "Test suite output handler\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTest\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCPPTEST_UNUSED\fP(x)   (void)x"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CPPTEST_UNUSED(x)   (void)x"

.PP
Definition at line 37 of file cpptest\-output\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
