.TH "cpptest-htmloutput.h" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpptest-htmloutput.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'cpptest\-collectoroutput\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTest::HtmlOutput\fP"
.br
.RI "HTML output\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTest\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
