.TH "cpptest-collectoroutput.h" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpptest-collectoroutput.h
.SH SYNOPSIS
.br
.PP
\fC#include <list>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'cpptest\-output\&.h'\fP
.br
\fC#include 'cpptest\-source\&.h'\fP
.br
\fC#include 'cpptest\-time\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTest::CollectorOutput\fP"
.br
.RI "Collector output\&. "
.ti -1c
.RI "struct \fBTest::CollectorOutput::TestInfo\fP"
.br
.ti -1c
.RI "struct \fBTest::CollectorOutput::SuiteInfo\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTest\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
