.TH "cpptest-textoutput.h" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpptest-textoutput.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <list>\fP
.br
\fC#include 'cpptest\-source\&.h'\fP
.br
\fC#include 'cpptest\-output\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTest::TextOutput\fP"
.br
.RI "Text output handler that outputs to the a stream\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTest\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
