.TH "dbTest" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTest::Suite\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdbTest\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetup\fP ()"
.br
.ti -1c
.RI "virtual void \fBtear_down\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBRecordProcessor\fP \fBprocessor\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file ConsoleApplication1\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "dbTest::dbTest ()\fC [inline]\fP"

.PP
Definition at line 112 of file ConsoleApplication1\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void dbTest::setup ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBTest::Suite\fP\&.
.PP
Definition at line 124 of file ConsoleApplication1\&.cpp\&.
.SS "virtual void dbTest::tear_down ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBTest::Suite\fP\&.
.PP
Definition at line 139 of file ConsoleApplication1\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBRecordProcessor\fP dbTest::processor\fC [protected]\fP"

.PP
Definition at line 122 of file ConsoleApplication1\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
