.TH "RecordProcessor.h" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RecordProcessor.h
.SH SYNOPSIS
.br
.PP
\fC#include <windows\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'sqlite3\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRecordProcessor\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBRecord\fP = vector< string >"
.br
.ti -1c
.RI "using \fBRecords\fP = vector< \fBRecord\fP >"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBRecord\fP =  vector<string>"

.PP
Definition at line 14 of file RecordProcessor\&.h\&.
.SS "using \fBRecords\fP =  vector<\fBRecord\fP>"

.PP
Definition at line 15 of file RecordProcessor\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
