.TH "sqlite3_rtree_geometry" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite3_rtree_geometry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sqlite3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBpContext\fP"
.br
.ti -1c
.RI "int \fBnParam\fP"
.br
.ti -1c
.RI "\fBsqlite3_rtree_dbl\fP * \fBaParam\fP"
.br
.ti -1c
.RI "void * \fBpUser\fP"
.br
.ti -1c
.RI "void(* \fBxDelUser\fP )(void *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8790 of file sqlite3\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsqlite3_rtree_dbl\fP* sqlite3_rtree_geometry::aParam"

.PP
Definition at line 8793 of file sqlite3\&.h\&.
.SS "int sqlite3_rtree_geometry::nParam"

.PP
Definition at line 8792 of file sqlite3\&.h\&.
.SS "void* sqlite3_rtree_geometry::pContext"

.PP
Definition at line 8791 of file sqlite3\&.h\&.
.SS "void* sqlite3_rtree_geometry::pUser"

.PP
Definition at line 8794 of file sqlite3\&.h\&.
.SS "void(* sqlite3_rtree_geometry::xDelUser) (void *)"

.PP
Definition at line 8795 of file sqlite3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
