.TH "sqlite3_file" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite3_file
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sqlite3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const struct \fBsqlite3_io_methods\fP * \fBpMethods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 667 of file sqlite3\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "const struct \fBsqlite3_io_methods\fP* sqlite3_file::pMethods"

.PP
Definition at line 668 of file sqlite3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
