.TH "sqlite3_index_info::sqlite3_index_orderby" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite3_index_info::sqlite3_index_orderby
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sqlite3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBiColumn\fP"
.br
.ti -1c
.RI "unsigned char \fBdesc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6215 of file sqlite3\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned char sqlite3_index_info::sqlite3_index_orderby::desc"

.PP
Definition at line 6217 of file sqlite3\&.h\&.
.SS "int sqlite3_index_info::sqlite3_index_orderby::iColumn"

.PP
Definition at line 6216 of file sqlite3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
