.TH "sqlite3_pcache_page" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite3_pcache_page
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sqlite3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBpBuf\fP"
.br
.ti -1c
.RI "void * \fBpExtra\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7395 of file sqlite3\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "void* sqlite3_pcache_page::pBuf"

.PP
Definition at line 7396 of file sqlite3\&.h\&.
.SS "void* sqlite3_pcache_page::pExtra"

.PP
Definition at line 7397 of file sqlite3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
