.TH "sqlite3_index_info::sqlite3_index_constraint" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite3_index_info::sqlite3_index_constraint
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sqlite3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBiColumn\fP"
.br
.ti -1c
.RI "unsigned char \fBop\fP"
.br
.ti -1c
.RI "unsigned char \fBusable\fP"
.br
.ti -1c
.RI "int \fBiTermOffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6208 of file sqlite3\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int sqlite3_index_info::sqlite3_index_constraint::iColumn"

.PP
Definition at line 6209 of file sqlite3\&.h\&.
.SS "int sqlite3_index_info::sqlite3_index_constraint::iTermOffset"

.PP
Definition at line 6212 of file sqlite3\&.h\&.
.SS "unsigned char sqlite3_index_info::sqlite3_index_constraint::op"

.PP
Definition at line 6210 of file sqlite3\&.h\&.
.SS "unsigned char sqlite3_index_info::sqlite3_index_constraint::usable"

.PP
Definition at line 6211 of file sqlite3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
