.TH "stdafx.h" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stdafx.h
.SH SYNOPSIS
.br
.PP
\fC#include 'targetver\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <tchar\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
