.TH "Test::CompilerOutput::InvalidFormat" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test::CompilerOutput::InvalidFormat \- Compiler output exception\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cpptest\-compileroutput\&.h>\fP
.PP
Inherits logic_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInvalidFormat\fP (const std::string &what)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Compiler output exception\&. 

Indicates that an invalid message format was given when creating a compiler output\&. The failing format may be retrieved using the what() method\&. 
.PP
Definition at line 61 of file cpptest\-compileroutput\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Test::CompilerOutput::InvalidFormat::InvalidFormat (const std::string & what)\fC [inline]\fP"

.PP
Definition at line 64 of file cpptest\-compileroutput\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
