.TH "Test::CollectorOutput::SuiteInfo" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test::CollectorOutput::SuiteInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cpptest\-collectoroutput\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSuiteInfo\fP (const std::string &name, int tests)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fB_name\fP"
.br
.ti -1c
.RI "int \fB_errors\fP"
.br
.ti -1c
.RI "\fBTests\fP \fB_tests\fP"
.br
.ti -1c
.RI "\fBTime\fP \fB_time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 79 of file cpptest\-collectoroutput\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Test::CollectorOutput::SuiteInfo::SuiteInfo (const std::string & name, int tests)"

.SH "Member Data Documentation"
.PP 
.SS "int Test::CollectorOutput::SuiteInfo::_errors"

.PP
Definition at line 82 of file cpptest\-collectoroutput\&.h\&.
.SS "std::string Test::CollectorOutput::SuiteInfo::_name"

.PP
Definition at line 81 of file cpptest\-collectoroutput\&.h\&.
.SS "\fBTests\fP Test::CollectorOutput::SuiteInfo::_tests"

.PP
Definition at line 83 of file cpptest\-collectoroutput\&.h\&.
.SS "\fBTime\fP Test::CollectorOutput::SuiteInfo::_time"

.PP
Definition at line 84 of file cpptest\-collectoroutput\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
