.TH "Test::Source" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test::Source \- Assertment source information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cpptest\-source\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSource\fP ()"
.br
.ti -1c
.RI "\fBSource\fP (const char *\fBfile\fP, unsigned int \fBline\fP, const char *msg)"
.br
.ti -1c
.RI "const std::string & \fBfile\fP () const"
.br
.ti -1c
.RI "unsigned int \fBline\fP () const"
.br
.ti -1c
.RI "const std::string & \fBmessage\fP () const"
.br
.ti -1c
.RI "const std::string & \fBsuite\fP () const"
.br
.ti -1c
.RI "const std::string & \fBtest\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSuite\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Assertment source information\&. 

Contains information about an assertment point\&. 
.PP
Definition at line 42 of file cpptest\-source\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Test::Source::Source ()"

.SS "Test::Source::Source (const char * file, unsigned int line, const char * msg)"

.SH "Member Function Documentation"
.PP 
.SS "const std::string& Test::Source::file () const"

.SS "unsigned int Test::Source::line () const"

.SS "const std::string& Test::Source::message () const"

.SS "const std::string& Test::Source::suite () const"

.SS "const std::string& Test::Source::test () const"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBSuite\fP\fC [friend]\fP"

.PP
Definition at line 44 of file cpptest\-source\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
