.TH "Test::CollectorOutput::TestInfo" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test::CollectorOutput::TestInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cpptest\-collectoroutput\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestInfo\fP (const std::string name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fB_name\fP"
.br
.ti -1c
.RI "\fBTime\fP \fB_time\fP"
.br
.ti -1c
.RI "bool \fB_success\fP: 1"
.br
.ti -1c
.RI "\fBSources\fP \fB_sources\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file cpptest\-collectoroutput\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Test::CollectorOutput::TestInfo::TestInfo (const std::string name)\fC [explicit]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string Test::CollectorOutput::TestInfo::_name"

.PP
Definition at line 68 of file cpptest\-collectoroutput\&.h\&.
.SS "\fBSources\fP Test::CollectorOutput::TestInfo::_sources"

.PP
Definition at line 72 of file cpptest\-collectoroutput\&.h\&.
.SS "bool Test::CollectorOutput::TestInfo::_success"

.PP
Definition at line 71 of file cpptest\-collectoroutput\&.h\&.
.SS "\fBTime\fP Test::CollectorOutput::TestInfo::_time"

.PP
Definition at line 69 of file cpptest\-collectoroutput\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
