.TH "Test::HtmlOutput" 3 "Mon Jan 22 2018" "Version 1.0" "NTS Homework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test::HtmlOutput \- HTML output\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cpptest\-htmloutput\&.h>\fP
.PP
Inherits \fBTest::CollectorOutput\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBgenerate\fP (std::ostream &os, bool incl_ok_tests=true, const std::string &name='')"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "struct \fBTestSuiteRow\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
HTML output\&. 

Output handler that creates a HTML table with detailed information about all tests\&. 
.PP
Definition at line 44 of file cpptest\-htmloutput\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Test::HtmlOutput::generate (std::ostream & os, bool incl_ok_tests = \fCtrue\fP, const std::string & name = \fC''\fP)"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend struct TestSuiteRow\fC [friend]\fP"

.PP
Definition at line 56 of file cpptest\-htmloutput\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NTS Homework from the source code\&.
